# Generated by Django 4.2.10 on 2024-02-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beverages", "0002_remove_beverage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverage",
            name="apk",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="beverage",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
