# Generated by Django 4.2.10 on 2024-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beverages", "0003_alter_beverage_apk_alter_beverage_price_per_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beverage",
            name="apk",
        ),
        migrations.RemoveField(
            model_name="beverage",
            name="price_per_unit",
        ),
        migrations.AddField(
            model_name="beverage",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
